confini/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),

]

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include(('ticket.urls', 'ticket'), namespace='ticket')),

# ]

confini/tickets/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import *


app_name = 'ticket'

urlpatterns = [
    path('', views.homepage, name='homepage'),
     path('nuevotick', views.CreateUser.as_view(), name='nuevotick'),
     path('user', views.listUser, name='user'),
     url(r'^editar/(?P<pk>\d+)/$', views.EditUser.as_view(), name="editar"),    
     path('eliminar/<int:id>/', views.deleteUser, name='eliminar'),

 ]

confini/usuarios/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('nuevoreg', views.CreateUser.as_view(), name='nuevoreg'),
    path('lista', views.listUser, name='lista'),
    url(r'^editar/(?P<pk>\d+)/$', views.EditUser.as_view(), name="editar"),    
    path('eliminar/<int:id>/', views.deleteUser, name='eliminar'),

]

confini/tickets/models.py
from django.db import models

# Create your models here.
class User(models.Model):
  
    usuario = models.CharField(max_length=100)
    inicio = models.CharField(max_length=200)
    fin = models.IntegerField()

    def __str__(self):
        return self.nombre.inicio

confini/usuarios/models.py
from django.db import models

# Create your models here.

class Usuario(models.Model):
  
    nombre = models.CharField(max_length=200)
    usuario = models.CharField(max_length=100)
    contraseña = models.CharField(max_length=200)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=10)

    def __str__(self):
        return self.nombre.usuario

confini/tickets/forms.py
from django import forms
from .models import *

class UserForm(forms.ModelForm):
    class Meta: 
        model = User
        fields = [
            'usuario',
            'inicio',
            'fin',
        ]

confini/usuarios/forms.py
from django import forms
from .models import *

class UsuarioForm(forms.ModelForm):
    class Meta: 
        model = Usuario
        fields = [
            'nombre',
            'usuario',
            'contraseña',
            'edad',
            'telefono',
        ]

confini/tickets/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from .models import *
from .forms import*

# Vista para los tickets
def homepage(request):
     user = User.objects.all()
     contexto = {
        'ticket':user
     }
     return render(request, "inicio/inicio.html", contexto)

class CreateUser(CreateView):
     model = User
     form_class = UserForm
     template_name = 'ticket/nuevotick.html'
     success_url = reverse_lazy('ticket:user')

def listUser(request):
     user = User.objects.all()
     contexto = {
        'usuario': user
     }
     return render(request, 'ticket/user.html', contexto)

class EditUser(UpdateView):
     model = User
     form_class = UserForm
     template_name  = 'ticket/editar.html'
     success_url = reverse_lazy('ticket:user')

def deleteUser(request, id):
     user = User.objects.get(id = id)
     user.delete()
     return redirect('ticket: user')

confini/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from .models import *
from .forms import*

# Create your views here.
def homepage(request):
    usuarios = Usuario.objects.all()
    contexto = {
        'usuario':usuarios
    }
    return render(request, "inicio/inicio.html", contexto)

class CreateUser(CreateView):
    model = Usuario
    form_class = UsuarioForm
    template_name = 'usuarios/nuevoreg.html'
    success_url = reverse_lazy('usuarios:lista')

def listUser(request):
    usuario = Usuario.objects.all()
    contexto = {
        'usuario': usuario
    }
    return render(request, 'usuarios/lista.html', contexto)

class EditUser(UpdateView):
    model = Usuario
    form_class = UsuarioForm
    template_name  = 'usuarios/editar.html'
    success_url = reverse_lazy('usuarios:lista')

def deleteUser(request, id):
    usuario = Usuario.objects.get(id = id)
    usuario.delete()
    return redirect('usuarios:lista')

confini/templates/inicio/include/barra.html
<style>
    .brand-logo{
        font-size: large;
    }

</style>
<nav>
    <div class="nav-wrapper cyan darken-1 ">
        <a href="{% url 'usuarios:lista' %}" class="brand-logo center ">SkySoftNet</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="{% url 'usuarios:lista' %}">Usuarios</a></li>
            <li><a href="{% url 'usuarios:user' %}">Tickets</a></li>
        </ul>
    </div>
</nav>

confini/templates/inicio/inicio.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block css %}
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />

        {% endblock css %}
    <title>SkySoftNet</title>
</head>

<body class="body light-blue lighten-5">
    
    {% include "inicio/include/barra.html" %}
    <div class="container">
        <br>
        {% block content %}
        {% endblock %}
    </div>

    {% block javascript %}
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
        integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    {% endblock javascript %}

</body>

</html>

confini/templates/tickets/editar.html
{% extends "inicio/inicio.html" %}
{% block content %}
<style>
    form {
        font-family: inherit;
        font-size: 100%;
    }
</style>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn cyan darken-1" type="submit">Editar</button>
</form>
{% endblock content %}

confini/templates/tickets/nuevotick.html
{% extends "inicio/inicio.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    {{ form|crispy }}
    <button class="btn cyan darken-1" type="submit">Nuevo</button>
</form>
{% endblock content %}

confini/templates/tickets/user.html
{% extends "inicio/inicio.html" %}
{% load static %}
{% block stylesheets %}
{{ block.super }}
<link href="/static/estilos.css" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
<style>

th {
    text-align: center;
}

td,
h5 {
    text-align: center;
    padding: 30px;
}

</style>

<h5>Generar Ticket</h5>
    <table class=responsive-table">
        <thead>
            <tr class="titulos blue lighten-3">

                <th>Usuario</th>
                <th>Fecha de Inicio</th>
                <th>Fecha de Fin</th>

            </tr>
        </thead>

        <tbody >
            {% for e in usuario %}
            <tr class="cuerpo  blue lighten-4">

                <td>{{e.usuario}}</td>
                <td>{{e.inicio}}</td>
                <td>{{e.fin}}</td>

                <td>
                    <a href="{% url 'usuarios:eliminar' e.id %}"><button class="btn cyan darken-1">ELIMINAR</button></a>
                    <a href="{% url 'usuarios:imprimir' e.id %}"><button class="btn cyan darken-2">Imprimir</button></a>
                </td>

            </tr>
            {% endfor %}

        </tbody>

    </table>
    <br>
    <a href="{% url 'usuarios:nuevotick' %}"><button class="btn cyan darken-1">NUEVO TICKET</button></a>
    {% endblock %}

confini/templates/usuarios/editar.html
{% extends "inicio/inicio.html" %}
{% block content %}
<style>
    form {
        font-family: inherit;
        font-size: 100%;
    }
</style>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn cyan darken-1" type="submit">Editar</button>
</form>
{% endblock content %}

confini/templates/usuarios/lista.html
{% extends "inicio/inicio.html" %}
{% load static %}
{% block stylesheets %}
{{ block.super }}
<link href="/static/estilos.css" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
<style>

th {
    text-align: center;
}

h5 {
    text-align: center;
    padding: 30px;
}

</style>

<h5>Lista de Usuarios</h5>
    <table class=responsive-table">
        <thead>
            <tr class="titulos blue lighten-3">

                <th>Nombre</th>
                <th>Usuario</th>
                <th>Contraseña</th>
                <th>Edad</th>
                <th>Teléfono</th>
                <th>Opciones</th>


            </tr>
        </thead>

        <tbody >
            {% for e in usuario %}
            <tr class="cuerpo  blue lighten-4">

                <td>{{e.nombre}}</td>
                <td>{{e.usuario}}</td>
                <td>{{e.contraseña}}</td>
                <td>{{e.edad}}</td>
                <td>{{e.telefono}}</td>

                <td><a href="{% url 'usuarios:editar' e.id %}"><button class="btn cyan darken-1">EDITAR</button></a>

                    <a href="{% url 'usuarios:eliminar' e.id %}"><button class="btn cyan darken-1">ELIMINAR</button></a>
                </td>

            </tr>
            {% endfor %}

        </tbody>

    </table>
    <br>
    <a href="{% url 'usuarios:nuevoreg' %}"><button class="btn cyan darken-1">NUEVO REGISRO</button></a>
    {% endblock %}

confini/templates/usuarios/nuevoreg.html
{% extends "inicio/inicio.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    {{ form|crispy }}
    <button class="btn cyan darken-1" type="submit">Nuevo</button>
</form>
{% endblock content %}